Family.create(:id => 1, :nome => "Datter", :descr => "Branca e Auro não são parentes próximos, ainda que sejam da mesma família.")
Family.create(:id => 2, :nome => "Delcan", :descr => "Todos os lideres de castelo do planeta Batalha são dessa família. (Mas não necessariamente irmãos.)")
Family.create(:id => 3, :nome => "Erathur", :descr => "Uma das famílias que integram o clã estilha negra. Essa família não é uma das mais importantes.")
Family.create(:id => 4, :nome => "Foldane")
Family.create(:id => 5, :nome => "Gama Blackfield", :descr => "Família da protagonista do nova era. A parte newkie é da mãe e a parte humana é do pai da Nidja.")
Family.create(:id => 6, :nome => "Kreer", :descr => "Uma das fámilias da tribo dos lobisomens vermelhos.\r\nSildon e Kalryne são irmãos. Kalryne é a mais nova.")
Family.create(:id => 7, :nome => "Lelin", :descr => "Foi essa familia que originalmente criou os felks.")
Family.create(:id => 8, :nome => "Mabert", :descr => "Uma família antiga e pouco conhecida aos dragões comuns. Geralmente seus membros tem atribuições importantes.")
Family.create(:id => 9, :nome => "Mainat", :descr => "Uma das famílias que integram o clã estilha negra. Essa família não é a mais importante, nem a menos.")
Family.create(:id => 10, :nome => "Morland")
Family.create(:id => 11, :nome => "Netrick", :descr => "Lyia é filha de Tieg e Lua, por ter sido simplesmente um \"presente\" da lua de Hollus (Luna), não tem realmente pais. Pode se dizer até que ela é adotada.")
Family.create(:id => 12, :nome => "Reaven", :descr => "Família do protagonista do newkies")
Family.create(:id => 13, :nome => "Ressek", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:id => 14, :nome => "Rettack", :descr => "Família do líder dos lobos vermelhos. Não se sabe se Nith tem algum parentesco com Rayka.")
Family.create(:id => 15, :nome => "Ristair", :descr => "Família do protagonista do ilhas de batalha. Alguns membros certamente vivem em Xuim, uma vila próxima a um penhasco.")
Family.create(:id => 16, :nome => "Roanim")
Family.create(:id => 17, :nome => "Rollinor", :descr => "Família do líder dos lobisomens brancos.")
Family.create(:id => 18, :nome => "Sashvaret", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:id => 19, :nome => "Sastar")
Family.create(:id => 20, :nome => "Shoukat")
Family.create(:id => 21, :nome => "Torcom")
Family.create(:id => 22, :nome => "Tuerem")
Family.create(:id => 23, :nome => "Tylladon", :descr => "Família do líder dos lobisomens negros. ")
Family.create(:id => 24, :nome => "Ducan")
Family.create(:id => 27, :nome => "Delta IV Beta X")
