Name.create(:id => 1, :nome => "Accith", :descr => "Lobisomem vermelho, caçador experiente.", :race_id => 3, :family_id => 18)
Name.create(:id => 2, :nome => "Aline", :descr => "Responsável geral pela educação mágica. (Cúpula techmaga)", :race_id => 1, :family_id => 24)
Name.create(:id => 3, :nome => "Anna", :descr => "Cabelo/Olho azuis claros. Originalmente ela havia sido salva por Vitur em Oram, e ficou psicologicamente dependente dele.", :race_id => 2)
Name.create(:id => 4, :nome => "Argon", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 5, :nome => "Amy", :descr => "Amy é a consciência nanorobôtica \"dele\", a única a ultrapassar as restrições de segurança comuns a outras consciências e se tornar capaz de fazer o que bem entender, até criar outra consciências por conta própria. Apesar de Amy ter criado várias outras entidades nanorobôticas para lhe ajudar, nenhuma delas entrou em contato direto com \"ele\".", :race_id => 9)
Name.create(:id => 6, :nome => "Arina", :descr => "Cabelo/olho laranjas. Se não me engano, ela era um newkie comandante protótipo, abandonada em estase em um dos tanques de imersão, no domo 2.", :race_id => 2)
Name.create(:id => 7, :nome => "Aura", :descr => "Concorrente de nidja no concurso de hegon, Cabelo e olho Verde claro liso, pintas azuis claras (404dp 16 anos)", :race_id => 2, :family_id => 25)
Name.create(:id => 8, :nome => "Auro", :descr => "Auro é o primeiro professor de combate de Branca.", :race_id => 4, :family_id => 1)
Name.create(:id => 9, :nome => "Branca", :descr => "Amiga do negro. Eles se conheceram no planeta batalha.", :race_id => 4, :family_id => 1)
Name.create(:id => 10, :nome => "Carim", :descr => "Carim é uma \"enfermeira\" que ajuda dragões que foram feridos na batalha contra Argon, o líder do quarto castelo da ilha suprema.", :race_id => 4, :family_id => 21)
Name.create(:id => 11, :nome => "Certh", :descr => "Dragão que se alia a negro no planeta batalha para tentar ultrapassar a ilha de Electro. A aliança não da certo.", :race_id => 4, :family_id => 16)
Name.create(:id => 12, :nome => "Cley", :descr => "Concorrente de Nidja no concurso de Hegon\r\nCabelo curto roxo e Olhos e pintas azuis ", :race_id => 2, :family_id => 26)
Name.create(:id => 13, :nome => "Cryoth", :descr => "Líder de um dos castelos do planeta batalha. Nome atualizado Gélido »» Cryoth", :race_id => 4, :family_id => 2)
Name.create(:id => 14, :nome => "Dallan Ilmuu Langrath", :descr => "Esse é o nome com que o personagem do Cristais se apresenta aos Techmagos.", :race_id => 6)
Name.create(:id => 15, :nome => "Draco", :descr => "Guardião do olho da sabedoria no planeta batalha", :race_id => 4, :family_id => 8)
Name.create(:id => 16, :nome => "Electro", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 17, :nome => "Gaulon", :descr => "Líder de um dos castelos do planeta batalha. Nome atualizado Preto »» Gaulon", :race_id => 4, :family_id => 2)
Name.create(:id => 18, :nome => "Hermy", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 19, :nome => "Icris", :descr => "Esse é o nome que Nagina usa para conversar com o personagem principal do Cristais. Ou esse era o nome original dele, ou era o nome que ele usava quando encontrou Nagina.", :race_id => 6)
Name.create(:id => 20, :nome => "Jadd", :descr => "Responsável por uma importante divisão de pesquisa militar. (Cúpula techmaga)", :race_id => 1, :family_id => 27)
Name.create(:id => 21, :nome => "Kalryne", :descr => "Lobisomem vermelha, irmã mais nova de Sildon. Ela é responsável por preparar temperos e remédios baseados em ervas para a tribo. (botânica - druida)", :race_id => 3, :family_id => 6)
Name.create(:id => 22, :nome => "Kuanos", :descr => "Líder Newkie, Dono original do Negro", :race_id => 2, :family_id => 28)
Name.create(:id => 23, :nome => "Lans", :descr => "Chefe da policia do quadrante; Cabelo/Olho/Pintas Azul acinzentado (404 dp 35 Anos.)", :race_id => 2, :family_id => 29)
Name.create(:id => 24, :nome => "Lao", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 25, :nome => "Lara", :descr => "Filha de Leucadio e <>, Vitur originalmente a encontra pela primeira vez num passeio a praia com os newkies, no Brasil. A história provavelmente vai ser bem diferente quando eu reescrevê-la.", :race_id => 1, :family_id => 7)
Name.create(:id => 26, :nome => "Leonardo", :descr => "Primeiro nome usado pelo personagem principal do cristais. Esse era o seu nome originalmente em Hollus.", :race_id => 6)
Name.create(:id => 27, :nome => "Léucadio", :descr => "Primeiro nome usado pelo personagem principal do cristais. Esse era o seu nome originalmente em Hollus.", :race_id => 1, :family_id => 7)
Name.create(:id => 28, :nome => "Ligy", :descr => "Cabelo/olho roxos. Controladora newkie. A segunda newkie criada por Vitur.", :race_id => 2)
Name.create(:id => 29, :nome => "Linea", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 30, :nome => "Lithos", :descr => "Filho de Stara", :race_id => 2, :family_id => 30)
Name.create(:id => 31, :nome => "Lua", :descr => "Lobisomem prateada. Garota escolhida para acabar com o \"grande evento x\"", :race_id => 3, :family_id => 11)
Name.create(:id => 32, :nome => "Lucia", :descr => "Lucia é a diretora da techcidade em Hollus.", :race_id => 1, :family_id => 10)
Name.create(:id => 33, :nome => "Luna", :descr => "O espírito da lua de Hollus", :race_id => 7)
Name.create(:id => 34, :nome => "Lyia", :descr => "Lobisomem Prateada. Ela é o primeiro contado \"dele\" com os lobisomens.\r\nFilha do líder do líder dourado (que também é o líder dos lobisomens prateados), ela é uma figura importante, e acompanha \"ele\" nas visitas ás outras tribos dos lobisomens. ", :race_id => 3, :family_id => 11)
Name.create(:id => 35, :nome => "Marin", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 36, :nome => "Morí", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 37, :nome => "Mynn", :descr => "Integrante de uma das equipes de exploração da união newkie. Negro a encontra rodeando a nave de exploração \"Terket\" a procura de alguma falha estrutural, os dois conversam, ficam amigos e Mynn convida Negro para participar de uma missão de exploração e eles acabam caindo no planeta batalha.", :race_id => 4, :family_id => 31)
Name.create(:id => 38, :nome => "Nagina", :descr => "Nagina é uma espada com consciência, criada há vários planos abaixo milênios atrás e que costuma ser fiel a apenas um mestre, o único que pode tocá-la. Nagina existe a talvez centenas de milênios, e é particularmente homicida. Seu propósito de existência é matar.", :race_id => 6)
Name.create(:id => 39, :nome => "Nautza", :descr => "líder de um dos castelos do planeta batalha. Nome atualizado Athena »» Nautza ", :race_id => 4, :family_id => 2)
Name.create(:id => 40, :nome => "Negro", :descr => "Protagonista do ilhas de batalha. Nasceu em Xuim, uma vila perto de um penhasco.", :race_id => 4, :family_id => 15)
Name.create(:id => 41, :nome => "Nesti", :descr => "O espírito da primeira lua de Wolmron-3 (a lua menor)", :race_id => 7)
Name.create(:id => 42, :nome => "Niagara", :descr => "Mãe de Nidja, Programadora do OM, Olho verde, Cabelo laranja, pintas Ciano", :race_id => 2, :family_id => 5)
Name.create(:id => 43, :nome => "Nidja", :descr => "Meio-newkie. Protagonista do nova era.\r\nOlho marrom, cabelo preto, SEM PINTAS", :race_id => 8, :family_id => 5)
Name.create(:id => 44, :nome => "Nith", :descr => "Lobisomem vermelha. Não se sabe se é parente de Rayka.", :race_id => 3, :family_id => 14)
Name.create(:id => 45, :nome => "Psíco", :descr => "Psíco cuida da grande biblioteca no planeta batalha. Ilha do Electro.", :race_id => 4, :family_id => 22)
Name.create(:id => 46, :nome => "Rayka", :descr => "Lobisomem vermelha. Rayka é a líder dos lobos vermelhos.", :race_id => 3, :family_id => 14)
Name.create(:id => 47, :nome => "Ress", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 48, :nome => "Rigo", :descr => "Pai da Nidja, Jardineiro do Jardim, Olho marrom, cabelo preto", :race_id => 2, :family_id => 5)
Name.create(:id => 49, :nome => "Rika", :descr => "Cabelo/olho vermelhos. Primeira newkie criada por Vitur", :race_id => 9)
Name.create(:id => 50, :nome => "Sideam", :descr => "Lobisomem branco. Sideam é o líder do lobisomens brancos.", :race_id => 3, :family_id => 17)
Name.create(:id => 51, :nome => "Sikeya", :descr => "O espírito da segunda lua de Wolmron-3 (a lua maior, habitável e lar designado para os lobos vermelhos.)", :race_id => 7)
Name.create(:id => 52, :nome => "Sildon", :descr => "Lobisomem vermelho, irmão mais velho de Kalryne", :race_id => 3, :family_id => 6)
Name.create(:id => 53, :nome => "Skyra", :descr => "Integrante do clã estrela negra que comete o crime de mostrar o esconderijo do clã no planeta batalha para Negro e Branca.", :race_id => 4, :family_id => 3)
Name.create(:id => 54, :nome => "Stara", :descr => "Mãe de Lithos.", :race_id => 2, :family_id => 30)
Name.create(:id => 55, :nome => "Syan", :descr => "Um dos techmagos responsável pelo estudo dos lobisomens.", :race_id => 1, :family_id => 4)
Name.create(:id => 56, :nome => "Tâmara", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 57, :nome => "Tami", :descr => "Integrante do clã estrela negra. Ela que levou Skyra sob custódia após encontra-la com Negro e Branca dentro do esconderijo do clã no planeta batalha.", :race_id => 4, :family_id => 9)
Name.create(:id => 58, :nome => "Tami", :descr => "O espírito da primeira lua de Dermis", :race_id => 7)
Name.create(:id => 59, :nome => "Terra", :descr => "A primeira techmaga encontrada por \"ele\" e responsável por encaminhá-lo aos techmagos. Morreu durante o \"grande evento x\", vítima de um dos guardiões da segunda arma mágica. Foi ainda ressuscitada pelos seres do nódulo interdimensional e controlada por aqueles seres, até finalmente ser morta por \"Ele\" que no evento da destruição do posto intra-dimencional.", :race_id => 1, :family_id => 20)
Name.create(:id => 60, :nome => "Thasani", :descr => "Thasani foi selada em uma pedra selo e libertada por Rayka, em um plano arquitetado por Sikeya. Os lobisomens vermelhos originalmente haviam entendido que Sikeya desejava testá-los, apresentando-lhes um oponente poderoso. No fim, \"Ele\" impediu que a batalha tivesse uma conclusão, percebendo que o espirito na verdade desejava que a Arkain fosse libertada e pudesse retornar para junto de seu povo.", :race_id => 5)
Name.create(:id => 61, :nome => "Tieg", :descr => "Lobisomem prateado/dourado. Tieg é o líder dourado e líder dos lobisomens prateados e é o lobo dourado.", :race_id => 3, :family_id => 11)
Name.create(:id => 62, :nome => "Tylanth", :descr => "Líder do castelo supremo no planeta batalha. ", :race_id => 4, :family_id => 2)
Name.create(:id => 63, :nome => "Uthos", :descr => "Lobisomem vermelho responsável pelo caldeirão de sangue, um dos sábios da tribo de Rayka. Ela sempre o consultou para pedir conselhos.", :race_id => 3, :family_id => 13)
Name.create(:id => 64, :nome => "Vitur", :descr => "Protagonista do Newkies. Originalmente ele era um descendente de Bruno, o cientista líder dos newkies e saiu a procura do domo ao encontrar um diário de seu avô. Na história nova vai ser algo bem diferente.", :race_id => 1, :family_id => 12)
Name.create(:id => 65, :nome => "Xaon", :descr => "Lobisomem negro. Xaon é o líder dos lobos Negros.", :race_id => 3, :family_id => 23)
Name.create(:id => 66, :nome => "Zara", :descr => "Techmaga responsável pelo estudo dos lobisomens.", :race_id => 1, :family_id => 19)
