Orb.create(:id => 1, :nome => "Aghaphos", :descr => "A estrela do sistema", :orb_type_id => 3)
Orb.create(:id => 2, :nome => "Batalha", :descr => "2 planeta do sistema\r\nPlaneta onde a história do ilhas de batalha acontece. Já houve uma tentativa de colonização aqui, mas por ser um planeta importante para os dragões, eles mantiveram o seu domínio. ", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 3, :nome => "Exos", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 4, :nome => "Foris", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 5, :nome => "Gatina", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 6, :nome => "Rainos", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 7, :nome => "Cinturão Koid", :descr => "Um dos cinturões de asteroides do sistema Foris.\r\nKoid é o cinturão interno, rico em recursos.", :orb_type_id => 4, :orbit_id => "4")
Orb.create(:id => 8, :nome => "Creator", :descr => "3 luas, (Rines) (Gravis) (Ruar)\r\nPlaneta newkie, população 8 milhões, 2 planeta do sistema.", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 9, :nome => "Dermis", :descr => "2 luas, (Tami) (Lua falsa)\r\nEsse planeta é o centro do império techmago. ", :orb_type_id => 1)
Orb.create(:id => 10, :nome => "Tami", :descr => "A primeira lua de dermis", :orb_type_id => 2, :orbit_id => "9")
Orb.create(:id => 11, :nome => "Frogis", :descr => "1 lua, ()\r\nPlaneta newkie, população 3 milhões.\r\n2º planeta do sistema. ", :orb_type_id => 1, :orbit_id => "1")
Orb.create(:id => 12, :nome => "Hegon", :descr => "Hegon é uma perola dos Plyorns, uma das centrais de contro dos portais, com uma peculiar orbita elíptica ao redor de Gatina. ", :orb_type_id => 5, :orbit_id => "5")
Orb.create(:id => 13, :nome => "Hollus", :descr => "1 lua, (Luna)\r\nEste planeta é o planeta onde a historia do livro Cristais começa, quando \"ele\" estava em um parque reclamando que a vida era muito comum e então duas naves, uma a serviço dos techmagos e com Terra na tripulação, entram em orbita e começam a se matar.\r\nEste também é o planeta onde os lobisomens e gat`arks originalmente habitavam. ", :orb_type_id => 1)
Orb.create(:id => 14, :nome => "Luna", :descr => "Única lua de Hollus.", :orb_type_id => 2, :orbit_id => "13")
Orb.create(:id => 15, :nome => "Irea", :descr => "0 luas\r\nPlaneta newkie\r\nPopulação 3 milhões\r\n2 planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 16, :nome => "Nokris", :descr => "0 luas.\r\n1 planeta do sistema\r\nPlaneta inabitável.", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 17, :nome => "Oroa", :descr => "1 lua, (Katis)\r\nPlaneta humana\r\nPopulação 200 milhões\r\n3 planeta do sistema\r\nA capital humana no nova era. ", :orb_type_id => 1, :orbit_id => "5")
Orb.create(:id => 18, :nome => "Katis", :descr => "Única lua de Oroa, usada como deposito de lixo.", :orb_type_id => 2, :orbit_id => "17")
Orb.create(:id => 19, :nome => "Radus", :descr => "0 luas.\r\n3 planeta do sistema.\r\nPlaneta inabitável. ", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 20, :nome => "Rãe", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 21, :nome => "Starats", :descr => "0 luas\r\nPlaneta humano\r\nPopulação 500 milhões\r\n1º planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 22, :nome => "UNCentury", :descr => "1 lua, (Lunis)\r\nPlaneta newkie, população aproximada 10 bilhões. Segundo planeta do sistema.\r\nEsse planeta se torna a capital da união newkie assim que eles abandonam o sistema solar.\r\nAno com 300 dias e dia com 30 horas. ", :orb_type_id => 1, :orbit_id => "5")
Orb.create(:id => 23, :nome => "Lunis", :descr => "Lua de UNcentury", :orb_type_id => 2, :orbit_id => "22")
Orb.create(:id => 24, :nome => "Unos", :descr => "2 luas, ()()\r\nPlaneta newkie\r\nPopulação 500 milhões\r\n1 planeta do sistema.\r\nColonia de mineração, que se aproveita dos numerosos asteroides do sistema.", :orb_type_id => 1, :orbit_id => "4")
Orb.create(:id => 25, :nome => "Utery", :descr => "0 luas\r\n1º planeta do sistema\r\nPlaneta inabitável", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 26, :nome => "Wolmron-3", :descr => "2 luas, (Wolmron-3-1, Nesti) (Wolmron-3-2, Sikeya)\r\nWolmrom-3 é um planeta afastado do eixo central do império techmago sem nenhum recurso valioso conhecido. Seu nome vem simplesmente da sua posição no sistema. (terceiro planeta)\r\nSendo um planeta habitável, ele é escolhido como possível novo lar para as tribos dos lobisomens.", :orb_type_id => 1, :orbit_id => "29")
Orb.create(:id => 27, :nome => "Wolmron-3-1 (Nesti)", :descr => "Lua inóspita de Wolmron.\r\nSeu nome original é originário da sua posição planetária. (primeira lua do terceiro planeta)\r\nQuando ocorre o contato com o espirito da lua desse planeta, ela se identificou como Nesti e esse se tornou o nome oficial da lua.\r\n", :orb_type_id => 2, :orbit_id => "26")
Orb.create(:id => 28, :nome => "Wolmron-3-2 (Sikeya)", :descr => "Grande lua habitável de Wolmron\r\nSeu nome original é originário da sua posição planetária. (Segunda lua do terceiro planeta)\r\nQuando ocorre o contato com o espirito da lua desse planeta, ela se identificou como Sikeya e esse se tornou o nome oficial da lua.\r\nEsse planeta era o lar original dos arkains, um povo que foi dizimado por piratas espaciais.", :orb_type_id => 2, :orbit_id => "26")
Orb.create(:id => 29, :nome => "Wolmron", :descr => "A estrela do sistema", :orb_type_id => 3)
Orb.create(:id => 30, :nome => "Xinos", :descr => "1 lua, (Agatha)\r\nPlaneta newkie, população aproximada 900 milhões\r\n2 planeta do sistema. ", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 31, :nome => "Agatha", :descr => "Lua de xinos", :orb_type_id => 2, :orbit_id => "30")
Orb.create(:id => 32, :nome => "Zeas", :descr => "1 luas. (Nyx)\r\nPlaneta newkie\r\nPopulação 4 milhões\r\n3 planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 33, :nome => "Nyx", :descr => "Lua de zeas", :orb_type_id => 2, :orbit_id => "32")
Orb.create(:id => 34, :nome => "Rines", :descr => "Lua de creator", :orb_type_id => 2, :orbit_id => "8")
Orb.create(:id => 35, :nome => "Gravis", :descr => "Lua de creator", :orb_type_id => 2, :orbit_id => "8")
Orb.create(:id => 36, :nome => "Ruar", :descr => "Lua de creator", :orb_type_id => 1, :orbit_id => "8")
