Race.create(:id => 1, :nome => "Humano", :descr => "Humanos são uma raça normal.")
Race.create(:id => 2, :nome => "Newkies", :descr => "Uma raça criada artificialmente. Pelos humanos.")
Race.create(:id => 3, :nome => "Lobisomem", :descr => "Raça originaria de Hollus capaz de se transformar na forma de um lobo.")
Race.create(:id => 4, :nome => "Dragão")
Race.create(:id => 5, :nome => "Arcain")
Race.create(:id => 6, :nome => "Consciência independente")
Race.create(:id => 7, :nome => "Espírito da lua")
Race.create(:id => 8, :nome => "Hibrido newkie-humano")
Race.create(:id => 9, :nome => "Nanorobô")
