ShipSize.create(:id => 1, :nome => "Nave de guerra")
ShipSize.create(:id => 2, :nome => "Cruzador")
ShipSize.create(:id => 3, :nome => "Estrela")
ShipSize.create(:id => 4, :nome => "Explorador")
ShipSize.create(:id => 5, :nome => "Transportador")
ShipSize.create(:id => 6, :nome => "Caça")
