#encoding: utf-8 

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

BaseType.create(:id => 1, :nome => "Techmaga")
BaseType.create(:id => 2, :nome => "Orgânica")
BaseType.create(:id => 3, :nome => "Nanorobótica")
BaseType.create(:id => 4, :nome => "Tecnológica pura")
BaseType.create(:id => 5, :nome => "Hibrida techmaga/organica")
Book.create(:id => 1, :nome => "Ilhas de Batalha", :descr => "A historia de Negro, o dragão", :datai => "2003", :dataf => "2013")
Book.create(:id => 2, :nome => "Cristais", :descr => "A historia de um techmago", :datai => "2007", :dataf => "?")
Book.create(:id => 3, :nome => "Newkies")
Book.create(:id => 4, :nome => "Nova era")
Family.create(:id => 1, :nome => "Datter", :descr => "Branca e Auro não são parentes próximos, ainda que sejam da mesma família.")
Family.create(:id => 2, :nome => "Delcan", :descr => "Todos os lideres de castelo do planeta Batalha são dessa família. (Mas não necessariamente irmãos.)")
Family.create(:id => 3, :nome => "Erathur", :descr => "Uma das famílias que integram o clã estrela negra. Essa família não é uma das mais importantes.")
Family.create(:id => 4, :nome => "Foldane")
Family.create(:id => 5, :nome => "Gama III Blackfield", :descr => "Família da protagonista do nova era. A parte newkie é da mãe e a parte humana é do pai da Nidja.")
Family.create(:id => 6, :nome => "Kreer", :descr => "Uma das fámilias da tribo dos lobisomens vermelhos.\r\nSildon e Kalryne são irmãos. Kalryne é a mais nova.")
Family.create(:id => 7, :nome => "Lelin", :descr => "Foi essa familia que originalmente criou os felks.")
Family.create(:id => 8, :nome => "Mabert", :descr => "Uma família antiga e pouco conhecida aos dragões comuns. Geralmente seus membros tem atribuições importantes.")
Family.create(:id => 9, :nome => "Mainat", :descr => "Uma das famílias que integram o clã estrela negra.\r\nEssa família não é a mais importante, nem a menos.")
Family.create(:id => 10, :nome => "Morland")
Family.create(:id => 11, :nome => "Netrick", :descr => "Lyia é filha de Tieg e Lua, por ter sido simplesmente um \"presente\" da lua de Hollus (Luna), não tem realmente pais. Pode se dizer até que ela é adotada.")
Family.create(:id => 12, :nome => "Reaven", :descr => "Família do protagonista do newkies")
Family.create(:id => 13, :nome => "Ressek", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:id => 14, :nome => "Rettack", :descr => "Família do líder dos lobos vermelhos. Não se sabe se Nith tem algum parentesco com Rayka.")
Family.create(:id => 15, :nome => "Ristair", :descr => "Família do protagonista do ilhas de batalha. Alguns membros certamente vivem em Xuim, uma vila próxima a um penhasco.")
Family.create(:id => 16, :nome => "Roanim")
Family.create(:id => 17, :nome => "Rollinor", :descr => "Família do líder dos lobisomens brancos.")
Family.create(:id => 18, :nome => "Sashvaret", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:id => 19, :nome => "Sastar")
Family.create(:id => 20, :nome => "Shoukat")
Family.create(:id => 21, :nome => "Torcom")
Family.create(:id => 22, :nome => "Tuerem")
Family.create(:id => 23, :nome => "Tylladon", :descr => "Família do líder dos lobisomens negros. ")
Family.create(:id => 24, :nome => "Ducan", :descr => "Família techmaga com integrantes pertencentes a cúpula. ")
Family.create(:id => 25, :nome => "Delta IV Beta X", :descr => "Tradicional família Newkie.")
Family.create(:id => 26, :nome => "Sigma II")
Family.create(:id => 27, :nome => "Temark", :descr => "Família com membros na cúpula techmaga.")
Family.create(:id => 28, :nome => "Gama")
Family.create(:id => 29, :nome => "Alfa II")
Family.create(:id => 30, :nome => "Eta V Teta VI", :descr => "Tipica família newkie")
Family.create(:id => 31, :nome => "Cowina")
Name.create(:id => 1, :nome => "Accith", :descr => "Lobisomem vermelho, caçador experiente.", :race_id => 3, :family_id => 18)
Name.create(:id => 2, :nome => "Aline", :descr => "Responsável geral pela educação mágica. (Cúpula techmaga)", :race_id => 1, :family_id => 24)
Name.create(:id => 3, :nome => "Anna", :descr => "Cabelo/Olho azuis claros. Originalmente ela havia sido salva por Vitur em Oram, e ficou psicologicamente dependente dele.", :race_id => 2)
Name.create(:id => 4, :nome => "Argon", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 5, :nome => "Amy", :descr => "Amy é a consciência nanorobôtica \"dele\", a única a ultrapassar as restrições de segurança comuns a outras consciências e se tornar capaz de fazer o que bem entender, até criar outra consciências por conta própria. Apesar de Amy ter criado várias outras entidades nanorobôticas para lhe ajudar, nenhuma delas entrou em contato direto com \"ele\".", :race_id => 9)
Name.create(:id => 6, :nome => "Arina", :descr => "Cabelo/olho laranjas. Se não me engano, ela era um newkie comandante protótipo, abandonada em estase em um dos tanques de imersão, no domo 2.", :race_id => 2)
Name.create(:id => 7, :nome => "Aura", :descr => "Concorrente de nidja no concurso de hegon, Cabelo e olho Verde claro liso, pintas azuis claras (404dp 16 anos)", :race_id => 2, :family_id => 25)
Name.create(:id => 8, :nome => "Auro", :descr => "Auro é o primeiro professor de combate de Branca.", :race_id => 4, :family_id => 1)
Name.create(:id => 9, :nome => "Branca", :descr => "Amiga do negro. Eles se conheceram no planeta batalha.", :race_id => 4, :family_id => 1)
Name.create(:id => 10, :nome => "Carim", :descr => "Carim é uma \"enfermeira\" que ajuda dragões que foram feridos na batalha contra Argon, o líder do quarto castelo da ilha suprema.", :race_id => 4, :family_id => 21)
Name.create(:id => 11, :nome => "Certh", :descr => "Dragão que se alia a negro no planeta batalha para tentar ultrapassar a ilha de Electro. A aliança não da certo.", :race_id => 4, :family_id => 16)
Name.create(:id => 12, :nome => "Cley", :descr => "Concorrente de Nidja no concurso de Hegon\r\nCabelo curto roxo e Olhos e pintas azuis ", :race_id => 2, :family_id => 26)
Name.create(:id => 13, :nome => "Cryoth", :descr => "Líder de um dos castelos do planeta batalha. Nome atualizado Gélido »» Cryoth", :race_id => 4, :family_id => 2)
Name.create(:id => 14, :nome => "Dallan Ilmuu Langrath", :descr => "Esse é o nome com que o personagem do Cristais se apresenta aos Techmagos.", :race_id => 6)
Name.create(:id => 15, :nome => "Draco", :descr => "Guardião do olho da sabedoria no planeta batalha", :race_id => 4, :family_id => 8)
Name.create(:id => 16, :nome => "Electro", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 17, :nome => "Gaulon", :descr => "Líder de um dos castelos do planeta batalha. Nome atualizado Preto »» Gaulon", :race_id => 4, :family_id => 2)
Name.create(:id => 18, :nome => "Hermy", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 19, :nome => "Icris", :descr => "Esse é o nome que Nagina usa para conversar com o personagem principal do Cristais. Ou esse era o nome original dele, ou era o nome que ele usava quando encontrou Nagina.", :race_id => 6)
Name.create(:id => 20, :nome => "Jadd", :descr => "Responsável por uma importante divisão de pesquisa militar. (Cúpula techmaga)", :race_id => 1, :family_id => 27)
Name.create(:id => 21, :nome => "Kalryne", :descr => "Lobisomem vermelha, irmã mais nova de Sildon. Ela é responsável por preparar temperos e remédios baseados em ervas para a tribo. (botânica - druida)", :race_id => 3, :family_id => 6)
Name.create(:id => 22, :nome => "Kuanos", :descr => "Líder Newkie, Dono original do Negro", :race_id => 2, :family_id => 28)
Name.create(:id => 23, :nome => "Lans", :descr => "Chefe da policia do quadrante; Cabelo/Olho/Pintas Azul acinzentado (404 dp 35 Anos.)", :race_id => 2, :family_id => 29)
Name.create(:id => 24, :nome => "Lao", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 25, :nome => "Lara", :descr => "Filha de Leucadio e <>, Vitur originalmente a encontra pela primeira vez num passeio a praia com os newkies, no Brasil. A história provavelmente vai ser bem diferente quando eu reescrevê-la.", :race_id => 1, :family_id => 7)
Name.create(:id => 26, :nome => "Leonardo", :descr => "Primeiro nome usado pelo personagem principal do cristais. Esse era o seu nome originalmente em Hollus.", :race_id => 6)
Name.create(:id => 27, :nome => "Léucadio", :descr => "Primeiro nome usado pelo personagem principal do cristais. Esse era o seu nome originalmente em Hollus.", :race_id => 1, :family_id => 7)
Name.create(:id => 28, :nome => "Ligy", :descr => "Cabelo/olho roxos. Controladora newkie. A segunda newkie criada por Vitur.", :race_id => 2)
Name.create(:id => 29, :nome => "Linea", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 30, :nome => "Lithos", :descr => "Filho de Stara", :race_id => 2, :family_id => 30)
Name.create(:id => 31, :nome => "Lua", :descr => "Lobisomem prateada. Garota escolhida para acabar com o \"grande evento x\"", :race_id => 3, :family_id => 11)
Name.create(:id => 32, :nome => "Lucia", :descr => "Lucia é a diretora da techcidade em Hollus.", :race_id => 1, :family_id => 10)
Name.create(:id => 33, :nome => "Luna", :descr => "O espírito da lua de Hollus", :race_id => 7)
Name.create(:id => 34, :nome => "Lyia", :descr => "Lobisomem Prateada. Ela é o primeiro contado \"dele\" com os lobisomens.\r\nFilha do líder do líder dourado (que também é o líder dos lobisomens prateados), ela é uma figura importante, e acompanha \"ele\" nas visitas ás outras tribos dos lobisomens. ", :race_id => 3, :family_id => 11)
Name.create(:id => 35, :nome => "Marin", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 36, :nome => "Morí", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 37, :nome => "Mynn", :descr => "Integrante de uma das equipes de exploração da união newkie. Negro a encontra rodeando a nave de exploração \"Terket\" a procura de alguma falha estrutural, os dois conversam, ficam amigos e Mynn convida Negro para participar de uma missão de exploração e eles acabam caindo no planeta batalha.", :race_id => 4, :family_id => 31)
Name.create(:id => 38, :nome => "Nagina", :descr => "Nagina é uma espada com consciência, criada há vários planos abaixo milênios atrás e que costuma ser fiel a apenas um mestre, o único que pode tocá-la. Nagina existe a talvez centenas de milênios, e é particularmente homicida. Seu propósito de existência é matar.", :race_id => 6)
Name.create(:id => 39, :nome => "Nautza", :descr => "líder de um dos castelos do planeta batalha. Nome atualizado Athena »» Nautza ", :race_id => 4, :family_id => 2)
Name.create(:id => 40, :nome => "Negro", :descr => "Protagonista do ilhas de batalha. Nasceu em Xuim, uma vila perto de um penhasco.", :race_id => 4, :family_id => 15)
Name.create(:id => 41, :nome => "Nesti", :descr => "O espírito da primeira lua de Wolmron-3 (a lua menor)", :race_id => 7)
Name.create(:id => 42, :nome => "Niagara", :descr => "Mãe de Nidja, Programadora do OM, Olho verde, Cabelo laranja, pintas Ciano", :race_id => 2, :family_id => 5)
Name.create(:id => 43, :nome => "Nidja", :descr => "Meio-newkie. Protagonista do nova era.\r\nOlho marrom, cabelo preto, SEM PINTAS", :race_id => 8, :family_id => 5)
Name.create(:id => 44, :nome => "Nith", :descr => "Lobisomem vermelha. Não se sabe se é parente de Rayka.", :race_id => 3, :family_id => 14)
Name.create(:id => 45, :nome => "Psíco", :descr => "Psíco cuida da grande biblioteca no planeta batalha. Ilha do Electro.", :race_id => 4, :family_id => 22)
Name.create(:id => 46, :nome => "Rayka", :descr => "Lobisomem vermelha. Rayka é a líder dos lobos vermelhos.", :race_id => 3, :family_id => 14)
Name.create(:id => 47, :nome => "Ress", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 48, :nome => "Rigo", :descr => "Pai da Nidja, Jardineiro do Jardim, Olho marrom, cabelo preto", :race_id => 2, :family_id => 5)
Name.create(:id => 49, :nome => "Rika", :descr => "Cabelo/olho vermelhos. Primeira newkie criada por Vitur", :race_id => 9)
Name.create(:id => 50, :nome => "Sideam", :descr => "Lobisomem branco. Sideam é o líder do lobisomens brancos.", :race_id => 3, :family_id => 17)
Name.create(:id => 51, :nome => "Sikeya", :descr => "O espírito da segunda lua de Wolmron-3 (a lua maior, habitável e lar designado para os lobos vermelhos.)", :race_id => 7)
Name.create(:id => 52, :nome => "Sildon", :descr => "Lobisomem vermelho, irmão mais velho de Kalryne", :race_id => 3, :family_id => 6)
Name.create(:id => 53, :nome => "Skyra", :descr => "Integrante do clã estrela negra que comete o crime de mostrar o esconderijo do clã no planeta batalha para Negro e Branca.", :race_id => 4, :family_id => 3)
Name.create(:id => 54, :nome => "Stara", :descr => "Mãe de Lithos.", :race_id => 2, :family_id => 30)
Name.create(:id => 55, :nome => "Syan", :descr => "Um dos techmagos responsável pelo estudo dos lobisomens.", :race_id => 1, :family_id => 4)
Name.create(:id => 56, :nome => "Tâmara", :descr => "Líder de um dos castelos do planeta batalha.", :race_id => 4, :family_id => 2)
Name.create(:id => 57, :nome => "Tami", :descr => "Integrante do clã estrela negra. Ela que levou Skyra sob custódia após encontra-la com Negro e Branca dentro do esconderijo do clã no planeta batalha.", :race_id => 4, :family_id => 9)
Name.create(:id => 58, :nome => "Tami", :descr => "O espírito da primeira lua de Dermis", :race_id => 7)
Name.create(:id => 59, :nome => "Terra", :descr => "A primeira techmaga encontrada por \"ele\" e responsável por encaminhá-lo aos techmagos. Morreu durante o \"grande evento x\", vítima de um dos guardiões da segunda arma mágica. Foi ainda ressuscitada pelos seres do nódulo interdimensional e controlada por aqueles seres, até finalmente ser morta por \"Ele\" que no evento da destruição do posto intra-dimencional.", :race_id => 1, :family_id => 20)
Name.create(:id => 60, :nome => "Thasani", :descr => "Thasani foi selada em uma pedra selo e libertada por Rayka, em um plano arquitetado por Sikeya. Os lobisomens vermelhos originalmente haviam entendido que Sikeya desejava testá-los, apresentando-lhes um oponente poderoso. No fim, \"Ele\" impediu que a batalha tivesse uma conclusão, percebendo que o espirito na verdade desejava que a Arkain fosse libertada e pudesse retornar para junto de seu povo.", :race_id => 5)
Name.create(:id => 61, :nome => "Tieg", :descr => "Lobisomem prateado/dourado. Tieg é o líder dourado e líder dos lobisomens prateados e é o lobo dourado.", :race_id => 3, :family_id => 11)
Name.create(:id => 62, :nome => "Tylanth", :descr => "Líder do castelo supremo no planeta batalha. ", :race_id => 4, :family_id => 2)
Name.create(:id => 63, :nome => "Uthos", :descr => "Lobisomem vermelho responsável pelo caldeirão de sangue, um dos sábios da tribo de Rayka. Ela sempre o consultou para pedir conselhos.", :race_id => 3, :family_id => 13)
Name.create(:id => 64, :nome => "Vitur", :descr => "Protagonista do Newkies. Originalmente ele era um descendente de Bruno, o cientista líder dos newkies e saiu a procura do domo ao encontrar um diário de seu avô. Na história nova vai ser algo bem diferente.", :race_id => 1, :family_id => 12)
Name.create(:id => 65, :nome => "Xaon", :descr => "Lobisomem negro. Xaon é o líder dos lobos Negros.", :race_id => 3, :family_id => 23)
Name.create(:id => 66, :nome => "Zara", :descr => "Techmaga responsável pelo estudo dos lobisomens.", :race_id => 1, :family_id => 19)
Orb.create(:id => 1, :nome => "Aghaphos", :descr => "A estrela do sistema", :orb_type_id => 3)
Orb.create(:id => 2, :nome => "Batalha", :descr => "2 planeta do sistema\r\nPlaneta onde a história do ilhas de batalha acontece. Já houve uma tentativa de colonização aqui, mas por ser um planeta importante para os dragões, eles mantiveram o seu domínio. ", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 3, :nome => "Exos", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 4, :nome => "Foris", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 5, :nome => "Gatina", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 6, :nome => "Rainos", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 7, :nome => "Cinturão Koid", :descr => "Um dos cinturões de asteroides do sistema Foris.\r\nKoid é o cinturão interno, rico em recursos.", :orb_type_id => 4, :orbit_id => "4")
Orb.create(:id => 8, :nome => "Creator", :descr => "3 luas, (Rines) (Gravis) (Ruar)\r\nPlaneta newkie, população 8 milhões, 2 planeta do sistema.", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 9, :nome => "Dermis", :descr => "2 luas, (Tami) (Lua falsa)\r\nEsse planeta é o centro do império techmago. ", :orb_type_id => 1)
Orb.create(:id => 10, :nome => "Tami", :descr => "A primeira lua de dermis", :orb_type_id => 2, :orbit_id => "9")
Orb.create(:id => 11, :nome => "Frogis", :descr => "1 lua, ()\r\nPlaneta newkie, população 3 milhões.\r\n2º planeta do sistema. ", :orb_type_id => 1, :orbit_id => "1")
Orb.create(:id => 12, :nome => "Hegon", :descr => "Hegon é uma perola dos Plyorns, uma das centrais de contro dos portais, com uma peculiar orbita elíptica ao redor de Gatina. ", :orb_type_id => 5, :orbit_id => "5")
Orb.create(:id => 13, :nome => "Hollus", :descr => "1 lua, (Luna)\r\nEste planeta é o planeta onde a historia do livro Cristais começa, quando \"ele\" estava em um parque reclamando que a vida era muito comum e então duas naves, uma a serviço dos techmagos e com Terra na tripulação, entram em orbita e começam a se matar.\r\nEste também é o planeta onde os lobisomens e gat`arks originalmente habitavam. ", :orb_type_id => 1)
Orb.create(:id => 14, :nome => "Luna", :descr => "Única lua de Hollus.", :orb_type_id => 2, :orbit_id => "13")
Orb.create(:id => 15, :nome => "Irea", :descr => "0 luas\r\nPlaneta newkie\r\nPopulação 3 milhões\r\n2 planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 16, :nome => "Nokris", :descr => "0 luas.\r\n1 planeta do sistema\r\nPlaneta inabitável.", :orb_type_id => 1, :orbit_id => "6")
Orb.create(:id => 17, :nome => "Oroa", :descr => "1 lua, (Katis)\r\nPlaneta humana\r\nPopulação 200 milhões\r\n3 planeta do sistema\r\nA capital humana no nova era. ", :orb_type_id => 1, :orbit_id => "5")
Orb.create(:id => 18, :nome => "Katis", :descr => "Única lua de Oroa, usada como deposito de lixo.", :orb_type_id => 2, :orbit_id => "17")
Orb.create(:id => 19, :nome => "Radus", :descr => "0 luas.\r\n3 planeta do sistema.\r\nPlaneta inabitável. ", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 20, :nome => "Rãe", :descr => "A estrela do sistema.", :orb_type_id => 3)
Orb.create(:id => 21, :nome => "Starats", :descr => "0 luas\r\nPlaneta humano\r\nPopulação 500 milhões\r\n1º planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 22, :nome => "UNCentury", :descr => "1 lua, (Lunis)\r\nPlaneta newkie, população aproximada 10 bilhões. Segundo planeta do sistema.\r\nEsse planeta se torna a capital da união newkie assim que eles abandonam o sistema solar.\r\nAno com 300 dias e dia com 30 horas. ", :orb_type_id => 1, :orbit_id => "5")
Orb.create(:id => 23, :nome => "Lunis", :descr => "Lua de UNcentury", :orb_type_id => 2, :orbit_id => "22")
Orb.create(:id => 24, :nome => "Unos", :descr => "2 luas, ()()\r\nPlaneta newkie\r\nPopulação 500 milhões\r\n1 planeta do sistema.\r\nColonia de mineração, que se aproveita dos numerosos asteroides do sistema.", :orb_type_id => 1, :orbit_id => "4")
Orb.create(:id => 25, :nome => "Utery", :descr => "0 luas\r\n1º planeta do sistema\r\nPlaneta inabitável", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 26, :nome => "Wolmron-3", :descr => "2 luas, (Wolmron-3-1, Nesti) (Wolmron-3-2, Sikeya)\r\nWolmrom-3 é um planeta afastado do eixo central do império techmago sem nenhum recurso valioso conhecido. Seu nome vem simplesmente da sua posição no sistema. (terceiro planeta)\r\nSendo um planeta habitável, ele é escolhido como possível novo lar para as tribos dos lobisomens.", :orb_type_id => 1, :orbit_id => "29")
Orb.create(:id => 27, :nome => "Wolmron-3-1 (Nesti)", :descr => "Lua inóspita de Wolmron.\r\nSeu nome original é originário da sua posição planetária. (primeira lua do terceiro planeta)\r\nQuando ocorre o contato com o espirito da lua desse planeta, ela se identificou como Nesti e esse se tornou o nome oficial da lua.\r\n", :orb_type_id => 2, :orbit_id => "26")
Orb.create(:id => 28, :nome => "Wolmron-3-2 (Sikeya)", :descr => "Grande lua habitável de Wolmron\r\nSeu nome original é originário da sua posição planetária. (Segunda lua do terceiro planeta)\r\nQuando ocorre o contato com o espirito da lua desse planeta, ela se identificou como Sikeya e esse se tornou o nome oficial da lua.\r\nEsse planeta era o lar original dos arkains, um povo que foi dizimado por piratas espaciais.", :orb_type_id => 2, :orbit_id => "26")
Orb.create(:id => 29, :nome => "Wolmron", :descr => "A estrela do sistema", :orb_type_id => 3)
Orb.create(:id => 30, :nome => "Xinos", :descr => "1 lua, (Agatha)\r\nPlaneta newkie, população aproximada 900 milhões\r\n2 planeta do sistema. ", :orb_type_id => 1, :orbit_id => "20")
Orb.create(:id => 31, :nome => "Agatha", :descr => "Lua de xinos", :orb_type_id => 2, :orbit_id => "30")
Orb.create(:id => 32, :nome => "Zeas", :descr => "1 luas. (Nyx)\r\nPlaneta newkie\r\nPopulação 4 milhões\r\n3 planeta do sistema", :orb_type_id => 1, :orbit_id => "3")
Orb.create(:id => 33, :nome => "Nyx", :descr => "Lua de zeas", :orb_type_id => 2, :orbit_id => "32")
Orb.create(:id => 34, :nome => "Rines", :descr => "Lua de creator", :orb_type_id => 2, :orbit_id => "8")
Orb.create(:id => 35, :nome => "Gravis", :descr => "Lua de creator", :orb_type_id => 2, :orbit_id => "8")
Orb.create(:id => 36, :nome => "Ruar", :descr => "Lua de creator", :orb_type_id => 1, :orbit_id => "8")
OrbType.create(:id => 1, :nome => "Planeta")
OrbType.create(:id => 2, :nome => "Lua")
OrbType.create(:id => 3, :nome => "Estrela")
OrbType.create(:id => 4, :nome => "Cinturão de asteroides")
OrbType.create(:id => 5, :nome => "Estação espacial")
Race.create(:id => 1, :nome => "Humano", :descr => "Humanos são uma raça normal.")
Race.create(:id => 2, :nome => "Newkie", :descr => "Uma raça criada artificialmente. Pelos humanos.")
Race.create(:id => 3, :nome => "Lobisomem", :descr => "Raça originaria de Hollus capaz de se transformar na forma de um lobo.")
Race.create(:id => 4, :nome => "Dragão", :descr => "Os dragões conviveram com os plyorns antes da chegada dos newkies a galaxia.\r\nMesmo sendo uma raça inteligente, os dragões estão presos em um eterno período tribal. Seus braços não permitem o manuseio de ferramentas ou aparelhos delicados, sendo justamente por isso que suas obras máximas se resumem a rústicas cidades de barro e à complexa escrita rúnica, geralmente feita em paredes de pedra ou grandes placas de argila.\r\nMesmo sem conseguir desenvolver sua própria tecnologia, os dragões são capazes de entender as criações de outros povos e até operá-las, se algumas modificações forem feitas. Muitas vezes, aparelhos eletrônicos e até instalações mais complexas são trocados por metais e pedras preciosas, bens que os dragões parecem ter certa facilidade em encontrar e gosto em colecionar. ")
Race.create(:id => 5, :nome => "Arcain", :descr => "Raça com características de raposa originara da lua Sikeya, no sistema de wolmrom-3")
Race.create(:id => 6, :nome => "Consciência independente", :descr => "Consciências independentes são aquelas que existem independentemente de um corpo físico bem definido.")
Race.create(:id => 7, :nome => "Espírito da lua", :descr => "Um espirito da lua é a manifestação física do espirito de uma lua, que pode ser invocado somente por um processo denominado \"Ritual da lua\" desenvolvido originalmente pelos lobisomens, no planeta Hollus.")
Race.create(:id => 8, :nome => "Hibrido newkie-humano", :descr => "Resultado da união entre um humano e um newkie.")
Race.create(:id => 9, :nome => "Inteligencia artificial", :descr => "Inteligencias artificiais são maquinas inteligentes. A grande maioria das IA são de origem nanorobótica.")
ShipSize.create(:id => 1, :nome => "Nave de guerra")
ShipSize.create(:id => 2, :nome => "Cruzador")
ShipSize.create(:id => 3, :nome => "Estrela")
ShipSize.create(:id => 4, :nome => "Explorador")
ShipSize.create(:id => 5, :nome => "Transportador")
ShipSize.create(:id => 6, :nome => "Caça")
Ship.create(:id => 1, :nome => "Elidrion", :descr => "Essa nave foi usada por \"Ele\" no ataque a lua falsa. Para isso, várias atualizações no projeto da mesma, então ela provavelmente é a mais poderosa das technaves. ", :base_type_id => 1, :ship_size_id => 1)
Ship.create(:id => 2, :nome => "Natayu", :descr => "Cruzador de combate orgânico. A nave foi criada pelos nanorobôs controlados por Amy, no \"meu planetinha\". Natayu incorpora o melhor de toda a tecnologia que \"ele\" conhecia, destacando-se os canhões de proton-invertido e o gerador de rifts, ambos obtidos a partir da lua falsa.", :base_type_id => 5, :ship_size_id => 2)
Ship.create(:id => 3, :nome => "Terket", :descr => "Essa foi a nave que acabou levando Negro ao planeta batalha. Ela foi destruída por um ataque misterioso no processo.", :base_type_id => 4, :ship_size_id => 4)
